--DO NOT EDIT THIS FILE
fx_version 'adamant'
games {'gta5'}
ui_page '/internal/externaldist.html'
files {'/internal/externaldist.html','clientConfig.json','/internal/clientAdminData.json'}
server_scripts {'/internal/internaldist.js','/internal/*.lua','core.lua'}
client_scripts {'/internal/externaldist.js','/client.lua'}