-- DO NOT EDIT THIS FILE.
-- THIS FILE IS A DEPEDENCY FOR THE DEFAULT PERMISSIONS.
-- ANY CHANGES TO THIS FILE CAN CORRUPT YOUR ANTICHEAT INSTALL.

-- Lynx Collective SRL Copyright 2022 - chocohax.net Romania

defaultPermissions = {
    ["adminmenu"] = "Access to the admin menu",
    ["ban"] = "Access to ban/tempban/unban command",
    ["cleararea"] = "Access to clear area command",
    ["chatProtection"] = "Bypass chatProtection checks",
    ["explosionProtection"] = "Bypass Explosions checks",
    ["fxparticlesProtection"] = "Bypass Server Sided fxParticles checks",
    ["weaponsProtection"] = "Bypass Server Sided weapons checks",
    ["entitiesProtection"] = "Bypass entity creation checks",
    ["clearpedtasksimmediatelyProtection"] = "Bypass ClearPedTasksImmediately checks",
    ["configs"] = "Access to configs commands",
    ["vehicles"] = "Access to vehicles commands",
    ["clientBypass"] = "Bypass clientProtection checks",
    ["getids"] = "Access to the getids (Get Identifiers) command",
    ["globalbanbypass"] = "Bypass Global Ban for your server",
    ["immune"] = "Prevent from getting kicked/banned by other administrators",
    ["kick"] = "Access to kick command",
    ["loginProtection"] = "Bypass any login Protection check",
    ["teleport"] = "Access to teleport command",
    ["weapons"] = "Access to weapons commands",
    ["esp"] = "Access the admin menu ESP feature",
    ["debugMenu"] = "Access the admin menu DEBUG MENU feature",
    ["screenshot"] = "Access to the admin menu SCREENSHOT feature and command",
    ["spectate"] = "Access to the admin menu SPECTATE feature"
}