-- DO NOT EDIT THIS FILE.
-- THIS FILE IS A DEPEDENCY FOR THE DEFAULT WEAPON NAMES.
-- ANY CHANGES TO THIS FILE CAN CORRUPT YOUR ANTICHEAT INSTALL.

-- Lynx Collective SRL Copyright 2022 - chocohax.net Romania

weaponNames = { 
    -- Melee
[`weapon_dagger`] = "weapon_dagger", -- Antique Cavalry Dagger
[`weapon_bat`] = "weapon_bat", -- Baseball Bat
[`weapon_bottle`] = "weapon_bottle", -- Broken Bottle
[`weapon_crowbar`] = "weapon_crowbar", -- Crowbar
[`weapon_flashlight`] = "weapon_flashlight", -- Flashlight
[`weapon_golfclub`] = "weapon_golfclub", -- Golf Club
[`weapon_hammer`] = "weapon_hammer", -- Hammer
[`weapon_hatchet`] = "weapon_hatchet", -- Hatchet
[`weapon_knuckle`] = "weapon_knuckle", -- Brass Knuckles
[`weapon_knife`] = "weapon_knife", -- Knife
[`weapon_machete`] = "weapon_machete", -- Machete
[`weapon_switchblade`] = "weapon_switchblade", -- Switchblade
[`weapon_nightstick`] = "weapon_nightstick", -- Nightstick
[`weapon_wrench`] = "weapon_wrench", -- Pipe Wrench
[`weapon_battleaxe`] = "weapon_battleaxe", -- Battle Axe
[`weapon_poolcue`] = "weapon_poolcue", -- Pool Cue
[`weapon_stone_hatchet`] = "weapon_stone_hatchet", -- Stone Hatchet

    -- Handguns
[`weapon_pistol`] = "weapon_pistol", -- Pistol
[`weapon_pistol_mk2`] = "weapon_pistol_mk2", -- Pistol Mk II
[`weapon_combatpistol`] = "weapon_combatpistol", -- Combat Pistol
[`weapon_appistol`] = "weapon_appistol", -- AP Pistol
[`weapon_stungun`] = "weapon_stungun", -- Stun Gun
[`weapon_pistol50`] = "weapon_pistol50", -- Pistol .50
[`weapon_snspistol`] = "weapon_snspistol", -- SNS Pistol
[`weapon_snspistol_mk2`] = "weapon_snspistol_mk2", -- SNS Pistol Mk II
[`weapon_heavypistol`] = "weapon_heavypistol", -- Heavy Pistol
[`weapon_vintagepistol`] = "weapon_vintagepistol", --  Vintage Pistol
[`weapon_flaregun`] = "weapon_flaregun", -- Flare Gun
[`weapon_marksmanpistol`] = "weapon_marksmanpistol", -- Marksman Pistol
[`weapon_revolver`] = "weapon_revolver", -- Heavy Revolver
[`weapon_revolver_mk2`] = "weapon_revolver_mk2", -- Heavy Revolver Mk II
[`weapon_doubleaction`] = "weapon_doubleaction", -- Double Action Revolver
[`weapon_raypistol`] = "weapon_raypistol", -- Up-n-Atomizer
[`weapon_ceramicpistol`] = "weapon_ceramicpistol", -- Ceramic Pistol
[`weapon_navyrevolver`] = "weapon_navyrevolver", -- Navy Revolver

    -- Submachine Guns
[`weapon_microsmg`] = "weapon_microsmg", -- Micro SMG
[`weapon_smg`] = "weapon_smg", -- SMG
[`weapon_smg_mk2`] = "weapon_smg_mk2", -- SMG Mk II
[`weapon_assaultsmg`] = "weapon_assaultsmg", -- Assault SMG
[`weapon_combatpdw`] = "weapon_combatpdw", -- Combat PDW
[`weapon_machinepistol`] = "weapon_machinepistol", -- Machine Pistol
[`weapon_minismg`] = "weapon_minismg", --  Mini SMG
[`weapon_raycarbine`] = "weapon_raycarbine", -- Unholy Hellbringer

    -- Shotguns
[`weapon_pumpshotgun`] = "weapon_pumpshotgun", -- Pump Shotgun
[`weapon_pumpshotgun_mk2`] = "weapon_pumpshotgun_mk2", -- Pump Shotgun Mk II
[`weapon_sawnoffshotgun`] = "weapon_sawnoffshotgun", -- Sawed-Off Shotgun
[`weapon_assaultshotgun`] = "weapon_assaultshotgun", -- Assault Shotgun
[`weapon_bullpupshotgun`] = "weapon_bullpupshotgun", -- Bullpup Shotgun
[`weapon_musket`] = "weapon_musket", -- Musket
[`weapon_heavyshotgun`] = "weapon_heavyshotgun", -- Heavy Shotgun
[`weapon_dbshotgun`] = "weapon_dbshotgun", -- Double Barrel Shotgun
[`weapon_autoshotgun`] = "weapon_autoshotgun", -- Sweeper Shotgun

    -- Assault Rifles
[`weapon_assaultrifle`] = "weapon_assaultrifle", -- Assault Rifle
[`weapon_assaultrifle_mk2`] = "weapon_assaultrifle_mk2", -- Assault Rifle Mk II
[`weapon_carbinerifle`] = "weapon_carbinerifle", -- Carbine Rifle
[`weapon_carbinerifle_mk2`] = "weapon_carbinerifle_mk2", -- Carbine Rifle Mk II
[`weapon_advancedrifle`] = "weapon_advancedrifle", -- Advanced Rifle
[`weapon_specialcarbine`] = "weapon_specialcarbine", -- Special Carbine
[`weapon_specialcarbine_mk2`] = "weapon_specialcarbine_mk2", -- Special Carbine Mk II
[`weapon_bullpuprifle`] = "weapon_bullpuprifle", -- Bullpup Rifle
[`weapon_bullpuprifle_mk2`] = "weapon_bullpuprifle_mk2", -- Bullpup Rifle Mk II
[`weapon_compactrifle`] = "weapon_compactrifle", -- Compact Rifle

    -- Light Machine Guns
[`weapon_mg`] = "weapon_mg", -- MG
[`weapon_combatmg`] = "weapon_combatmg", -- Combat MG
[`weapon_combatmg_mk2`] = "weapon_combatmg_mk2", -- Combat MG Mk II
[`weapon_gusenberg`] = "weapon_gusenberg", -- Gusenberg Sweeper

    -- Sniper Rifles
[`weapon_sniperrifle`] = "weapon_sniperrifle", -- Sniper Rifle
[`weapon_heavysniper`] = "weapon_heavysniper", -- Heavy Sniper
[`weapon_heavysniper_mk2`] = "weapon_heavysniper_mk2", -- Heavy Sniper Mk II
[`weapon_marksmanrifle`] = "weapon_marksmanrifle", -- Marksman Rifle
[`weapon_marksmanrifle_mk2`] = "weapon_marksmanrifle_mk2", -- Marksman Rifle Mk II

    -- Heavy Weapons
[`weapon_rpg`] = "weapon_rpg", -- RPG
[`weapon_rpg_2`] = "weapon_rpg_2", -- RPG 2
[1752584910] = "weapon_rpg_2_2", -- RPG 2 wtf 2
[`weapon_grenadelauncher`] = "weapon_grenadelauncher", -- Grenade Launcher
[`weapon_grenadelauncher_smoke`] = "weapon_grenadelauncher_smoke", -- Smoke Grenade Launcher
[`weapon_minigun`] = "weapon_minigun", -- Minigun
[`weapon_firework`] = "weapon_firework", -- Firework Launcher
[`weapon_railgun`] = "weapon_railgun", -- Railgun
[`weapon_hominglauncher`] = "weapon_hominglauncher", -- Homing Launcher
[`weapon_compactlauncher`] = "weapon_compactlauncher", -- Compact Grenade Launcher
[`weapon_rayminigun`] = "weapon_rayminigun", -- Widowmaker

    -- Throwables
[`weapon_grenade`] = "weapon_grenade", -- Grenade
[`weapon_bzgas`] = "weapon_bzgas", -- BZGas
[`weapon_molotov`] = "weapon_molotov", -- Molotov
[`weapon_stickybomb`] = "weapon_stickybomb", -- Sticky poop
[`weapon_proxmine`] = "weapon_proxmine", -- Proximity Mine
[`weapon_snowball`] = "weapon_snowball", -- Snow CBT
[`weapon_pipebomb`] = "weapon_pipebomb", -- Pipe Bomb
[`weapon_ball`] = "weapon_ball", -- Ball (Baseball ball)
[`weapon_smokegrenade`] = "weapon_smokegrenade", -- Smoke Grenade
[`weapon_flare`] = "weapon_flare", -- WOOSH flare

    --Miscellaneous
[`weapon_petrolcan`] = "weapon_petrolcan", -- Jerry Can
[`gadget_parachute`] = "gadget_parachute", -- Parachute
[`weapon_fireextinguisher`] = "weapon_fireextinguisher", -- Fire Extinguisher
[`weapon_hazardcan`] = "weapon_hazardcan", -- Hazardous Jerry Can

}